### PR TITLE
mod/game (fix rtl) very basic "fix" so all games can be displayed in RTL...

### PR DESCRIPTION
**Pull request by nadavkav**
... mode aligned to the left to prevent absolute positioning breakage

### CODE REVIEW

**Comment by nadavkav** [comment]
Any updates on this issue?

**Comment by nadavkav** [comment]
Any updates on this issue?

**Comment by bdaloukas** [comment]
I included it.

**Comment by nadavkav** [comment]
That was an initial one.
The second one, https://github.com/bdaloukas/moodle-mod_game/pull/4
is better.

**Pull request closed without merging**
