### PR TITLE
adding composer.json

### PR DESCRIPTION
**Pull request by danielneis**
Hello,

this adds composer.json to your plugin so people can install it using composer (getcomposer.org).

If you have any questions, please take a look at:

https://moodle.org/mod/forum/discuss.php?d=275466
https://tracker.moodle.org/browse/MDL-48114
https://moodle.org/mod/forum/discuss.php?d=312215

Kind regards,
Daniel

### CODE REVIEW

**Comment by danielneis** [comment]
Hello,

since i've written to you, 10 modules have merged the composer.json file.
It would be nice to add yours to the list =)

https://github.com/gjb2048/moodle-theme_essential/pull/513
https://github.com/gjb2048/moodle-format_grid/pull/17
https://github.com/FMCorz/moodle-block_xp/pull/19
https://github.com/justinhunt/moodle-repository_poodll/pull/1
https://github.com/danpoltawski/moodle-repository_github/pull/2
https://github.com/bmbrands/theme_bootstrap/pull/367
https://github.com/jcrodriguez-dis/moodle-mod_vpl/pull/6
https://github.com/bostelm/moodle-mod_scheduler/pull/21
https://github.com/danmarsden/moodle-mod_attendance/pull/67
https://github.com/danmarsden/moodle-block_attendance/pull/9

Kind regards,
Daniel

**Comment by renerbaffa** [comment]
Hello Daniel.

Here is the project I'm working on:
https://github.com/LOA-SEAD/remarmoodle/commits/master

Unfortunately I've cloned your repository and did some changes but later I had to rebase the repository to there. But I still have the stating code with the reference for yours here:
https://github.com/renerbaffa/moodle-mod_remar

So I don't have the reference for you anymore
Sorry
:(

**Comment by bdaloukas** [comment]
I included composer.json. Please take a look if it is ok.

**Comment by danielneis** [comment]
Hello,

it looks good. Thank you very much.
You may now consider registering you repository on https://packagist.org/ so people can take fully advantage of the tools =)

Kind regards,
Daniel

**Comment by bdaloukas** [comment]
I registered it. Is ok now?

**Comment by danielneis** [comment]
Yes, perfect!

**Pull request closed without merging**
